#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,5,9,29,42,43,61&i=1,2,3,4,15,16,17,35,36,37,38&v=21,15,22,23,27,26,25,18,19,-1,-1 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU
#define DSP_MODEL			DSP_ST7796
#define DSP_HSPI			true
#define TFT_DC			21
#define TFT_CS			15
#define TFT_RST			22
#define BRIGHTNESS_PIN			23
#define TS_MODEL			TS_MODEL_FT6336U
#define TS_SDA			18
#define TS_SCL			19
// 39 = SENSOR_VN
#define TS_INT			39
#define TS_RST			-1


#endif
